export const OVERLAY_WINDOW_WIDTH_COMPACT = 340;
export const OVERLAY_WINDOW_WIDTH_EXPANDED = 400;

export const OVERLAY_WINDOW_HEIGHT_COMPACT = 132;
export const OVERLAY_WINDOW_HEIGHT_EXPANDED = 154;

export const OVERLAY_WINDOW_SHOW_DURATION_MS = 400;
export const OVERLAY_WINDOW_HIDE_DURATION_MS = 300;
export const OVERLAY_WINDOW_ANIMATION_DURATION_MS = 300;

export const OVERLAY_WINDOW_MAX_BLUR_RADIUS = 4;
export const OVERLAY_WINDOW_INITIAL_SCALE = 0.9;

export const OVERLAY_WINDOW_ROOT_PADDING_TOP = 22;
export const OVERLAY_WINDOW_ROOT_PADDING_BOTTOM = 36;

export const OVERLAY_WINDOW_TOP_MARGIN = 48;
export const OVERLAY_WINDOW_HORIZONTAL_MARGIN = 0;
export const OVERLAY_WINDOW_BOTTOM_MARGIN = 0;
